### ISSUE TITLE
Generate example for `time` format

### ISSUE THREAD

**Issue by magicmatatjahu** [Redocly/openapi-sampler#120]
This is a feature request.

Would be great if lib supports generation example for `time` format, like in spec:

```json
{
  "type": "string",
  "format": "time"
}
```

and then output should be:

```text
14:15:22
```

At the moment lib supports generation for `date` and `date-time`, but `time` should be also supported. As I know `format` is a open value, so it shouldn't be against the OpenAPI specification [link](https://swagger.io/docs/specification/data-models/data-types/#string), but maybe there are issues as to why `time` format is not documented.

We have a reported issue in our library (which uses `openapi-sampler`) to supports `time` format and we don't want to make example inside library, but want to have support in used package.

I can make PR for it if you'll accept my request :)

Btw. Very helpful library :)

**Comment by adamaltman** [comment]
What about time zone properties? For example `+00:00`?

**Comment by c-pius** [comment]
openapi-sampler uses `Z` notation for time offset in `date-time`. so I guess [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6) `full-time` with `Z` time offset would make sense?

https://github.com/Redocly/openapi-sampler/blob/d60caddfdc9bbefdb1acf6fc0eb381d90aefbcce/src/samplers/string.js#L21
https://github.com/Redocly/openapi-sampler/blob/d60caddfdc9bbefdb1acf6fc0eb381d90aefbcce/src/utils.js#L10

**Comment by magicmatatjahu** [comment]
Exactly as @c-pius wrote. For example `15:59:60-08:00` will mean `15:59:60` time, 8 hours behind UTC.

Additionally, following with the [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6) there should be `partial-time` (`time` should use this format, but I don't know if this is a good idea -> ref: https://github.com/OAI/OpenAPI-Specification/issues/845) format without offset and `full-time` with offset.

**Comment by adamaltman** [comment]
I think it would be better to use a format of "partial-time" or "full-time" for clarity and alignment with the RFC 3339.

**Comment by c-pius** [comment]
@magicmatatjahu you are right, even appears like the discussions from your reference lean towards `time` format using `partial-time` from the RFC?

I don't really have an opinion whether `time` should use `partial-time` or `full-time`. Also not sure if it is a good idea to provide different formats "partial-time" and "full-time".

**Comment by magicmatatjahu** [comment]
@c-pius "partial-time" and "full-time" should be provide for this same cases like `date` and `date-time`, I mean you should have possibility to define time without timezone and with timezone. If there will be only `full-time` for example, then specifying time with a zero offset (if an offset is not needed) may be confusing

I can create PR for that, but after read the issue, which I mentioned it might be better to wait for the official support for the `time` format or for the format registry.

**Comment by magicmatatjahu** [comment]
As I see the `time` format is added in https://github.com/Redocly/openapi-sampler/pull/122 PR, so I close the issue, thanks!
