### ISSUE TITLE
Support format keyword

### ISSUE THREAD

**Issue by XVincentX** [Redocly/openapi-sampler#62]
Apparently OpenAPI sampler is ignoring the `format` keyword for numbers/integers — which leads to incorrect examples when they are specified.

**Comment by RomanHotsiy** [comment]
Could you provide more details?
OpenAPI Sampler always returns the integer numbers which should be valid for any number/integer `format`.

It may output non-integer numbers in the following cases:
- a non-integer value is specified in `enum` or `default`
- a non-integer value is specified in `minimum` or/and `maximum`

I am going to fix the second case (as the first is more schema issue). I just wanted to confirm you are hitting exactly this issue.

Thanks

**Comment by XVincentX** [comment]
Sure!

I am fundamentally working with this schema and apparently OpenAPI sampler is ignoring the `format` keyword

```json
{
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    }
  }
}
```

**Comment by RomanHotsiy** [comment]
So what do you mean by ignoring the `format` keyword? What sample does openapi-sampler produce for the schema above? I just tried and it produces:

```json
{
  "id": 0
}
```

which is correct (0 is `int64`). What results do you get?

**Comment by XVincentX** [comment]
This was totally my mistake. Sorry, my configuration was just not correct.
