### ISSUE TITLE
devDependencies include many obsolete packages

### ISSUE THREAD

**Issue by MikeRalphson** [Redocly/openapi-sampler#8]
Also `npm i` reports

> found 15 vulnerabilities (6 low, 5 moderate, 4 high)

**Comment by philsturgeon** [comment]
@RomanHotsiy can you enable @dependabot?

**Comment by RomanHotsiy** [comment]
Fixed. Sorry for the huge delay.
New package version (`1.0.0-beta.15`) should [land soon](https://travis-ci.org/Redocly/openapi-sampler/builds/547777084)

Thanks for suggestion @philsturgeon. Enabled @deppandabot 👍
