### ISSUE TITLE
Crash inside allOf.js

### ISSUE THREAD

**Issue by ThePainnn** [Redocly/openapi-sampler#90]
Got a crash in allOf.js

import { traverse } from './traverse';
import { mergeDeep } from './utils';

```
export function allOfSample(into, children, options, spec) {
  let res = traverse(into, options, spec);
  const subSamples = [];

  for (let subSchema of children) {
    const { type, readOnly, writeOnly, value } = traverse({ type, ...subSchema }, options, spec);
    if (res.type && type && type !== res.type) {
      throw new Error('allOf: schemas with different types can\'t be merged');
    }
```

which yeild: ReferenceError: Cannot access 'type' before initialization (at the second traverse call)
SubSchema is:
`[$ref: "#/components/schemas/cursor"]`

Where does type come from in the second traverse function? There is something I'm missing since that code passed you're test before.

**Comment by RomanHotsiy** [comment]
fixed by https://github.com/Redocly/openapi-sampler/commit/7c4c9a00f5a561ff091c2124902454bb090318d2

**Comment by RomanHotsiy** [comment]
Released in beta.16

**Comment by nlundquist** [comment]
Was this fixed? Looking at the code `const { type, readOnly, writeOnly, value } = traverse({ type, ...subSchema }, options, spec);` the `type` on the RHS of the equation is still referenced before initialization and is causing an error for me locally.
